### ISSUE TITLE
Error starting in HA version 2021.10.2

### ISSUE THREAD

**Issue by mdesin1974** [tuya/tuya-home-assistant#544]
**Describe the bug**
Hello.
Tuya_v2 integration is not working in HA version 2021.10.2.
There is error in HA logs (when i try to configure tuya_v2 integration via setup master (master is not showing too) ):

Error occurred loading configuration flow for integration tuya_v2: cannot import name 'ProjectType' from 'tuya_iot' (/usr/local/lib/python3.9/site-packages/tuya_iot/__init__.py)

**Home Assistant Version**
2021.10.2
