### ISSUE TITLE
running error on my raspberry ha. how to work?

### ISSUE THREAD

**Issue by liantianji** [tuya/tuya-home-assistant#160]
login success.But not any devices in ha.
running error on my raspberry ha. how to work?
version:1.3.2
Home Assistant Version: core-2021.2.3
log:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 246, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 162, in _init_tuya_sdk
    await cleanup_device_registry(hass)
  File "/config/custom_components/tuya_v2/__init__.py", line 179, in cleanup_device_registry
    device_registry = hass.helpers.device_registry.async_get(hass)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 642, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get'

**Comment by tbratfisch** [comment]
probably like your hassio-version is too old (looks like async_get was introduced in 2021.7.something), try updating it!

**Comment by liantianji** [comment]
When I upgrade HA to 2021.5.3. It is work.
